# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-04 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lighthousedjango.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('hashed_password', models.CharField(max_length=500)),
                ('blocked_websites', models.CharField(max_length=1000)),
                ('totals', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lighthousedjango.User'),
        ),
    ]
