# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-03 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthousedjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=75)),
                ('last', models.CharField(max_length=75)),
                ('hashed_password', models.CharField(max_length=500)),
                ('blocked_websites', models.CharField(max_length=1000)),
                ('totals', models.CharField(max_length=1000)),
            ],
        ),
    ]
