# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-04 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lighthousedjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
    ]
