# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-03 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lighthousedjango', '0002_auto_20180203_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='settings',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
