# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-03 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthousedjango', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
