# Generated by Django 2.0.2 on 2018-02-04 04:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lighthousedjango', '0004_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='lighthousedjango.Calendar'),
            preserve_default=False,
        ),
    ]
